### ISSUE TITLE
Error while opening file in MacOS mojave 

### ISSUE THREAD

**Issue by SethuSenthil** [codebytere/nodemessage#2]
(node:62969) UnhandledPromiseRejectionWarning: Error: SQLITE_CANTOPEN: unable to open database file

I believe this error is present because apple phrases the file with a .db extension, this can be escaped while duplicating the file with a .sqlite extension

**Comment by codebytere** [comment]
Yes! This is caused by Apple's move towards more secure filesystem permissions. You can fix this by adding your command line application (iTerm, Terminal, Hyper, whatever) to Full Disk Access in:
System Preferences > Security & Privacy > Privacy > Full Disk Access
